<?php
namespace RecordsMan;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-24 at 20:33:20.
 */
class PureSqlConditionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PureSqlCondition
     */
    protected $condition;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->condition = PureSqlCondition::create('`a`=5');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers RecordsMan\PureSqlCondition::compile
     * @todo   Implement testCompile().
     */
    public function testCompile()
    {
        // Remove the following lines when you implement this test.
        $this->assertEquals('(`a`=5)', $this->condition->compile());
    }

    /**
     * @covers RecordsMan\PureSqlCondition::test
     * @todo   Implement testTest().
     */
    public function testTest()
    {
        $this->setExpectedException('RecordsMan\RecordsManException', '', 30);
        $this->condition->test(['a' => 5]);
    }
}
